### ISSUE TITLE
to fix error in "Slack Notify on Star" Job under GitHub Actions 

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/scoop-bucket#18]
## Description
Under **GitHub Actions** of this repository **"[Slack Notify on Star](https://github.com/meshery/scoop-bucket/actions/runs/6325335076)"** job is failing for which [Slack.yaml](https://github.com/meshery/scoop-bucket/blob/master/.github/workflows/slack.yml) is to be Updated.

## Fix
To fix this issue, update the code of [slack.yaml](https://github.com/meshery/scoop-bucket/blob/master/.github/workflows/slack.yml) just by copy/pasting the code from[ slack.yaml](https://github.com/meshery/meshery/blob/master/.github/workflows/slack.yml) of [meshery](https://github.com/meshery/meshery)

**Comment by captain-Akshay** [comment]
please assign this one to me !

**Comment by coder12git** [comment]
@saurabh100ni I Want to work on this,

**Comment by saurabh100ni** [comment]
@coder12git on the fair basis let's get this assigned to @captain-Akshay.
I wonder if we have more issues for you to work on 👀

**Comment by coder12git** [comment]
> @coder12git on the fair basis let's get this assigned to @captain-Akshay. I wonder if we have more issues for you to work on 👀

Yeah, it's fine :)
